#!/bin/bash

# This scripts gets the router model. That name shall be placed in a dictionary used by json-creator.
# https://github.com/Akira25/json-creator

ROUTER=$(ssh root@frei.funk "grep machine /proc/cpuinfo | cut -d':' -f 2 | cut -c 2-")
echo "$ROUTER"
echo "$ROUTER" >> routermodel.txt
echo "written router model to routermodel.txt"
echo ""
